server:
  port: 9520
spring:
  datasource:
    url: jdbc:mysql:///onlyoffice?characterEncoding=UTF-8&useUnicode=true&useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
mybatis-plus:
  mapper-locations: classpath*:classpath*:com/ninelock/api/**/xml/*Mapper.xml
  global-config:
    banner: false
    db-config:
      id-type: AUTO
      table-underline: true
      logic-delete-value: 0
      logic-not-delete-value: 1
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    auto-mapping-behavior: full
    map-underscore-to-camel-case: true
#Mybatis输出sql日志
logging:
  level:
    org.jeecg.modules.system.mapper: debug